apiVersion: v1                       # api版本
kind: Service                        # 资源类型
metadata:                            # service的属性
  name: nignx-service                # service的名字
spec:
  type: NodePort                    # 对外暴露端口
  ports:
    - port: 80                      # Service端口，与docker的端口保持一致
      nodePort: 30001               # 暴露给外部的端口
  selector:
    app: nginx                      # 被选择的pod的标签
